[GLOBAL]
pants_version = "2.10.0"
backend_packages = [
    "pants.backend.experimental.go",
    "pants.backend.docker",
    "pants.backend.shell",
    "pants.backend.shell.lint.shfmt",
    "pants.backend.shell.lint.shellcheck",
    "pants.backend.python",
    "pants.backend.plugin_development",
    "proto_compile",
    "gomock",
]
pythonpath = ["%(buildroot)s/pants-plugins"]
use_deprecated_python_macros = false

[source]
root_patterns = [
    "pants-plugins",
]

[anonymous-telemetry]
enabled = false 

[golang]
expected_version = "1.18"
